### ISSUE TITLE
Error: Cannot find module 'daisyui' [Windows User]

### ISSUE THREAD

**Issue by ariandanim** [rizafahmi/eventflow#10]
```
Error: Cannot find module 'daisyui'
Require stack:
- c:\Users\app\phoenix\eventflow\assets\tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Function.resolve (C:\snapshot\tailwindcss\standalone-cli\patch-require.js:34:38)
    at _resolve (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:251148)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:253746)
    at c:\Users\app\phoenix\eventflow\assets\tailwind.config.js:22:5
    at evalModule (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:256443)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:254371)
    at C:\snapshot\tailwindcss\lib\lib\load-config.js:52:30 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\app\\phoenix\\eventflow\\assets\\tailwind.config.js'
  ]
}
```

If getting error like this when using Windows 11, just try type in your command prompt like this :
`npm install daisyui`

**Comment by rizafahmi** [comment]
Thank you for reporting this. DaisyUI installation should being added to README
